### ISSUE TITLE
Colocar acesso de memória com malloc e free

### ISSUE THREAD

**Issue by anamgholandadev** [neylanepl/engLinguagens-nelores#37]

**Comment by giooogk** [comment]
// Estrutura para um nó da árvore binária de busca
typedef struct Node {
    int chave;
    struct Node *esquerda, *direita;
}

// Função para criar um novo nó
Node* novoNo(int chave) {
    Node* temp = (Node*)malloc(sizeof(Node));
    temp->chave = chave;
    temp->esquerda = temp->direita = NULL;
    return temp;
}

// Função para inserir um novo nó na árvore binária de busca
Node* inserir(Node* root, int chave) {
    if (root == NULL) return novoNo(chave);
    if (chave < root->chave)
        root->esquerda = inserir(root->esquerda, chave);
    else if (chave > root->chave)
        root->direita = inserir(root->direita, chave);
    return root;
}

// Função para encontrar o nó com a chave mínima
void encontrarMinimo(Node* root, int* minChave, int* nivel, int atualNivel) {
    if (root == NULL) return;
    if (root->esquerda == NULL) {
        *minChave = root->chave;
        *nivel = atualNivel;
        return;
    }
    encontrarMinimo(root->esquerda, minChave, nivel, atualNivel + 1);
}

// Função para encontrar o nó com a chave máxima
void encontrarMaximo(Node* root, int* maxChave, int* nivel, int atualNivel) {
    if (root == NULL) return;
    if (root->direita == NULL) {
        *maxChave = root->chave;
        *nivel = atualNivel;
        return;
    }
    encontrarMaximo(root->direita, maxChave, nivel, atualNivel + 1);
}

// Função para imprimir a árvore nível a nível
void imprimirNivel(Node* root, int nivel) {
    if (root == NULL) return;
    if (nivel == 1) {
        printf("%d ", root->chave);
    } else if (nivel > 1) {
        imprimirNivel(root->esquerda, nivel - 1);
        imprimirNivel(root->direita, nivel - 1);
    }
}

int altura(Node* root) {
    if (root == NULL) return 0;
    else {
        int alturaEsquerda = altura(root->esquerda);
        int alturaDireita = altura(root->direita);
        if (alturaEsquerda > alturaDireita) return(alturaEsquerda + 1);
        else return(alturaDireita + 1);
    }
}

void imprimirArvore(Node* root) {
    int h = altura(root);
    for (int i = 1; i <= h; i++) {
        imprimirNivel(root, i);
        printf("\n");
    }
}

int main() {
    Node* root = NULL;
    int n, chave;

    // Inserção de valores na árvore
    printf("Digite o número de valores a serem inseridos: ");
    scanf("%d", &n);
    printf("Digite os valores:\n");
    for (int i = 0; i < n; i++) {
        scanf("%d", &chave);
        root = inserir(root, chave);
    }

    // Encontrar a chave mínima e seu nível
    int minChave = 0, minNivel = 0;
    encontrarMinimo(root, &minChave, &minNivel, 1);
    printf("A chave mínima é %d e está no nível %d.\n", minChave, minNivel);

    // Encontrar a chave máxima e seu nível
    int maxChave = 0, maxNivel = 0;
    encontrarMaximo(root, &maxChave, &maxNivel, 1);
    printf("A chave máxima é %d e está no nível %d.\n", maxChave, maxNivel);

    // Imprimir a árvore nível a nível
    printf("A árvore de busca, nível a nível, é:\n");
    imprimirArvore(root);

    return 0;
}
